[application]
title = "MindUp"
enabled = true
access_token = "OTpFVytjgoRuUpoBACruBcBmxXmREVnmjFMhqAwfJdfQ8amoqkJxJncWZMVo9mGe"

[permissions]
required = ["database", "client_http"]
allowed = ["database", "client_http"]

[database]
path = "mindup.db"
